[package]
name = "wasm-test"
edition = "2024"
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
sui-execution.workspace = true
sui-protocol-config.workspace = true
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
object_store.workspace = true
sui-types.workspace = true
prometheus.workspace = true
wasi = "0.14.7+wasi-0.2.4"
base64 = { workspace = true }
bcs = { workspace = true }
wit-bindgen = "0.47.0"
serde = { version = "1.0.228", features = ["derive"] }

[lints]
workspace = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
