[package]
name = "wasm-test"
edition = "2024"
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
sui-execution.workspace = true
sui-move-build.workspace = true
sui-protocol-config.workspace = true
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-package.workspace = true
move-compiler.workspace = true
move-command-line-common.workspace = true
move-ir-types.workspace = true
object_store.workspace = true
sui-types.workspace = true
prometheus.workspace = true
wasi.workspace = true
base64 = { workspace = true }
bcs = { workspace = true }
wit-bindgen = "0.47.0"
serde = { version = "1.0.228", features = ["derive"] }
vfs = "0.10.0"

[lints]
workspace = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
