package wasm-test:main;

world init {
    export init: func();
}

world execute {
    record transaction-effects {
        executed-epoch: u64,
        status: transaction-status,
        object-changes: list<transaction-object-change>
    }

    variant transaction-status {
        success,
        failure(transaction-status-failure)
    }

    record transaction-status-failure {
        error: string,
        command: option<u32>
    }

    variant id-operation {
        none,
        created,
        deleted,
    }

    record transaction-object-change {
        id: list<u8>,
        input-version: option<u64>,
        input-digest: option<list<u8>>,
        output-version: option<u64>,
        output-digest: option<list<u8>>,
        id-operation: id-operation,
    }

    export execute: func(transaction: list<u8>) -> transaction-effects;
}

world client {
    record shared-ownership {
        initial-shared-version: u64,
    }

    record consensus-ownership {
        start-version: u64,
        owner: list<u8>,
    }

    variant ownership {
        address-owner(list<u8>),
        object-owner(list<u8>),
        shared(shared-ownership),
        immutable,
        consensus(consensus-ownership),
    }

    record move-object-data {
        type-bcs: list<u8>,
        type-repr: string,
        has-public-transfer: bool,
        version: u64,
        contents: list<u8>,
    }

    record module-bytes {
        name: string,
        bytes: list<u8>,
    }

    record package-type-origin {
        module-name: string,
        datatype-name: string,
        package-id: list<u8>,
    }

    record package-link {
        original-package-id: list<u8>,
        upgraded-id: list<u8>,
        upgraded-version: u64,
    }

    record package-object-data {
        id: list<u8>,
        version: u64,
        modules: list<module-bytes>,
        type-origin-table: list<package-type-origin>,
        linkage-table: list<package-link>,
    }

    variant object-data {
        move-object(move-object-data),
        move-package(package-object-data),
    }

    record sui-object {
        id: list<u8>,
        version: u64,
        digest: list<u8>,
        data: object-data,
        owner: ownership,
        previous-transaction: list<u8>,
        storage-rebate: u64,
    }

    export get-objects-for-address: func(address: list<u8>) -> list<sui-object>;
    export get-object: func(id: list<u8>) -> option<sui-object>;
    export faucet: func(recipient: list<u8>, amount: u64) -> sui-object;
}

world move-package {
    // abilities
    enum ability { copy, drop, store, key }
    record ability-set { abilities: list<ability> }

    record normalized-struct-type {
        address: string,
        module: string,
        name: string,
        type-arguments: list<list<u8>>,
    }

    record normalized-struct-type-parameter {
        constraints: ability-set,
        is-phantom: bool,
    }

    record normalized-struct {
        abilities: ability-set,
        type-parameters: list<normalized-struct-type-parameter>,
        fields: list<list<u8>>,
    }

    record normalized-enum {
        abilities: ability-set,
        type-parameters: list<normalized-struct-type-parameter>,
        variants: list<normalized-enum-variant>,
    }

    record normalized-enum-variant {
        name: string,
        fields: list<list<u8>>,
    }

    enum normalized-visibility { private, public, friend }

    record normalized-function {
        visibility: normalized-visibility,
        is-entry: bool,
        type-parameters: list<ability-set>,
        parameters: list<list<u8>>,
        return: list<list<u8>>,
    }

    record normalized-module-id {
        address: string,
        name: string,
    }

    record normalized-module {
        file-format-version: u32,
        address: string,
        name: string,
        friends: list<normalized-module-id>,
        structs: list<normalized-module-pair>,
        enums: list<normalized-module-enum-pair>,
        exposed-functions: list<normalized-module-function-pair>,
    }

    record normalized-module-pair {
        name: string,
        data: normalized-struct,
    }

    record normalized-module-enum-pair {
        name: string,
        data: normalized-enum,
    }

    record normalized-module-function-pair {
        name: string,
        data: normalized-function,
    }

    export get-normalized-package: func(modules: list<list<u8>>) -> list<normalized-module>;
}
