package wasm-test:main;

world init {
    export init: func();
}

world execute {
    record transaction-effects {
        executed-epoch: u64,
        status: transaction-status,
        object-changes: list<transaction-object-change>
    }

    variant transaction-status {
        success,
        failure(transaction-status-failure)
    }

    record transaction-status-failure {
        error: string,
        command: option<u32>
    }

    variant id-operation {
        none,
        created,
        deleted,
    }

    record transaction-object-change {
        id: list<u8>,
        input-version: option<u64>,
        input-digest: option<list<u8>>,
        output-version: option<u64>,
        output-digest: option<list<u8>>,
        id-operation: id-operation,
    }

    record sui-transaction-block-effects {
        status: transaction-status,
        executed-epoch: u64,
        gas-used: gas-cost-summary,
        transaction-digest: list<u8>,
        created: list<owned-object-ref>,
        mutated: list<owned-object-ref>,
        unwrapped: list<owned-object-ref>,
        deleted: list<sui-object-ref>,
        unwrapped-then-deleted: list<sui-object-ref>,
        wrapped: list<sui-object-ref>,
        gas-object: owned-object-ref,
        dependencies: list<list<u8>>,
    }

    record gas-cost-summary {
        computation-cost: u64,
        storage-cost: u64,
        storage-rebate: u64,
        non-refundable-storage-fee: u64,
    }

    record owned-object-ref {
        reference: sui-object-ref,
        owner: ownership,
    }

    record sui-object-ref {
        object-id: list<u8>,
        version: u64,
        digest: list<u8>,
    }

    variant ownership {
        address-owner(list<u8>),
        object-owner(list<u8>),
        shared(shared-ownership),
        immutable,
        consensus-address(consensus-address-ownership)
    }

    record shared-ownership {
        initial-shared-version: u64,
    }

    record consensus-address-ownership {
        start-version: u64,
        owner: list<u8>
    }

    record sui-transaction-block-response {
        digest: list<u8>,
        effects: option<sui-transaction-block-effects>,
        object-changes: list<object-change>,
        raw-effects: list<u8>,
    }

    variant object-change {
        published(object-change-published),
        transferred(object-change-transferred),
        mutated(object-change-mutated),
        deleted(object-change-deleted),
        wrapped(object-change-wrapped),
        created(object-change-created),
    }

    record object-change-published {
        package-id: list<u8>,
        version: u64,
        digest: list<u8>,
        modules: list<string>,
    }

    record object-change-transferred {
        sender: list<u8>,
        recipient: ownership,
        object-type: string,
        object-id: list<u8>,
        version: u64,
        digest: list<u8>,
    }

    record object-change-mutated {
        sender: list<u8>,
        owner: ownership,
        object-type: string,
        object-id: list<u8>,
        version: u64,
        previous-version: u64,
        digest: list<u8>,
    }

    record object-change-deleted {
        sender: list<u8>,
        object-type: string,
        object-id: list<u8>,
        version: u64,
    }

    record object-change-wrapped {
        sender: list<u8>,
        object-type: string,
        object-id: list<u8>,
        version: u64,
    }

    record object-change-created {
        sender: list<u8>,
        owner: ownership,
        object-type: string,
        object-id: list<u8>,
        version: u64,
        digest: list<u8>,
    }

    export execute: func(transaction: list<u8>) -> sui-transaction-block-response;
    export dry-run-execute: func(transaction: list<u8>) -> sui-transaction-block-response;
}

world client {
    record shared-ownership {
        initial-shared-version: u64,
    }

    record consensus-ownership {
        start-version: u64,
        owner: list<u8>,
    }

    variant ownership {
        address-owner(list<u8>),
        object-owner(list<u8>),
        shared(shared-ownership),
        immutable,
        consensus(consensus-ownership),
    }

    record move-object-data {
        type-bcs: list<u8>,
        type-repr: string,
        has-public-transfer: bool,
        version: u64,
        contents: list<u8>,
    }

    record module-bytes {
        name: string,
        bytes: list<u8>,
    }

    record package-type-origin {
        module-name: string,
        datatype-name: string,
        package-id: list<u8>,
    }

    record package-link {
        original-package-id: list<u8>,
        upgraded-id: list<u8>,
        upgraded-version: u64,
    }

    record package-object-data {
        id: list<u8>,
        version: u64,
        modules: list<module-bytes>,
        type-origin-table: list<package-type-origin>,
        linkage-table: list<package-link>,
    }

    variant object-data {
        move-object(move-object-data),
        move-package(package-object-data),
    }

    record sui-object {
        id: list<u8>,
        version: u64,
        digest: list<u8>,
        data: object-data,
        owner: ownership,
        previous-transaction: list<u8>,
        storage-rebate: u64,
    }

    export get-objects-for-address: func(address: list<u8>) -> list<sui-object>;
    export get-object: func(id: list<u8>) -> option<sui-object>;
    export faucet: func(recipient: list<u8>, amount: u64) -> sui-object;
}

world move-package {
    // abilities
    enum ability { copy, drop, store, key }
    record ability-set { abilities: list<ability> }

    // parser definitions (subset of Move AST)
    enum move-visibility { public, friend, move-package, internal }

    record move-type { repr: string }

    record move-type-parameter {
        name: string,
        constraints: ability-set,
    }

    record move-parameter {
        name: string,
        is-mutable: bool,
        move-type: move-type,
    }

    record move-function {
        name: string,
        visibility: move-visibility,
        is-entry: bool,
        is-native: bool,
        type-parameters: list<move-type-parameter>,
        parameters: list<move-parameter>,
        returns: list<move-type>,
    }

    record move-field { name: string, move-type: move-type }

    variant move-struct-fields {
        named(list<move-field>),
        positional(list<move-type>),
        native,
    }

    record move-struct {
        name: string,
        is-native: bool,
        fields: move-struct-fields,
    }

    variant move-variant-fields {
        named(list<move-field>),
        positional(list<move-type>),
        empty,
    }

    record move-enum-variant {
        name: string,
        fields: move-variant-fields,
    }

    record move-enum {
        name: string,
        variants: list<move-enum-variant>,
    }

    record move-constant {
        name: string,
    }

    record move-use-decl {
        text: string,
    }

    record move-friend {
        module: string,
    }

    variant move-module-member {
        function(move-function),
        struct(move-struct),
        enumeration(move-enum),
        constant(move-constant),
        module-use(move-use-decl),
        friend(move-friend),
        spec(string),
    }

    record move-module {
        address: option<string>,
        name: string,
        members: list<move-module-member>,
    }
    record move-address {
        address: string,
        modules: list<move-module>,
    }
    variant move-definition {
        module(move-module),
        address(move-address),
    }

    record normalized-struct-type {
        address: string,
        module: string,
        name: string,
        type-arguments: list<list<u8>>,
    }

    record normalized-field {
        name: string,
        move-type: list<u8>,
    }

    record normalized-struct-type-parameter {
        constraints: ability-set,
        is-phantom: bool,
    }

    record normalized-struct {
        abilities: ability-set,
        type-parameters: list<normalized-struct-type-parameter>,
        fields: list<normalized-field>,
    }

    record normalized-enum {
        abilities: ability-set,
        type-parameters: list<normalized-struct-type-parameter>,
        variants: list<normalized-enum-variant>,
    }

    record normalized-enum-variant {
        name: string,
        fields: list<normalized-field>,
    }

    enum normalized-visibility { private, public, friend }

    record normalized-function {
        visibility: normalized-visibility,
        is-entry: bool,
        type-parameters: list<ability-set>,
        parameters: list<list<u8>>,
        return: list<list<u8>>,
    }

    record normalized-module-id {
        address: string,
        name: string,
    }

    record normalized-module {
        file-format-version: u32,
        address: string,
        name: string,
        friends: list<normalized-module-id>,
        structs: list<normalized-module-pair>,
        enums: list<normalized-module-enum-pair>,
        exposed-functions: list<normalized-module-function-pair>,
    }

    record normalized-module-pair {
        name: string,
        data: normalized-struct,
    }

    record normalized-module-enum-pair {
        name: string,
        data: normalized-enum,
    }

    record normalized-module-function-pair {
        name: string,
        data: normalized-function,
    }

    export get-normalized-package: func(modules: list<list<u8>>) -> list<normalized-module>;
    export get-definitions: func(move-code: string) -> list<move-definition>;
}

world build {
    enum severity {
        note,
        warning,
        nonblocking-error,
        blocking-error,
        bug,
    }

    enum diagnostics-format {
        text,
        json,
    }

    record diagnostic-info {
        severity: severity,
        category: u8,
        code: u8,
        external-prefix: option<string>,
        message: string,
    }

    record location {
        file-hash: list<u8>,
        start: u32,
        end: u32,
    }

    record diagnostic-label {
        location: location,
        message: string,
    }

    record diagnostic {
        info: diagnostic-info,
        primary-label: diagnostic-label,
        secondary-labels: list<diagnostic-label>,
        notes: list<string>,
    }

    record diagnostics {
        format: diagnostics-format,
        diagnostics: list<diagnostic>,
        filtered-source-diagnostics: list<diagnostic>,
    }

    record build-result {
        dependency-ids: list<list<u8>>,
        compiled-modules: list<list<u8>>,
        warning-diagnostics: diagnostics,
    }

    record build-error {
        message: string,
        diagnostics: diagnostics,
    }

    export build-package: func(
        path: string,
        install-dir: string,
        system-packages-path: string,
    ) -> result<build-result, build-error>;
}
